export const ACTIVITIES = [
  '"A" Levels',
  '"A" Levels (at discretion)',
  '15 Mins "quickie"',
  'Anal Play',
  'Bareback*',
  'BDSM*',
  'BDSM (giving)*',
  'BDSM (receiving)*',
  'Being Filmed',
  'Bukkake',
  'Car Meets',
  'CIM',
  'CIM (at discretion)',
  'Cross Dressing',
  'Deep Throat',
  'Depilation',
  'Dinner Dates',
  'Disabled Clients',
  'Dogging',
  'Domination*',
  'Domination (giving)*',
  'Domination (receiving)*',
  'Double Penetration',
  'Enema',
  'Exhibitionism',
  'Face Sitting',
  'Facials',
  'Female Ejaculation',
  'Fetish',
  'FFM 3Somes',
  'Fingering/Finger Play',
  'Food Sex/Sploshing',
  'Foot Worship',
  'French Kissing',
  'French Kissing (discretion)',
  'Gang Bangs',
  'Hand Relief',
  'Humiliation',
  'Humiliation (giving)',
  'Humiliation (receiving)',
  'Lapdancing',
  'Massage',
  'Milking/Lactating',
  'MMF 3Somes',
  'Modeling',
  'Moresomes',
  'Naturism/Nudism',
  'Oral',
  'Oral without (at discretion)',
  'Oral without Protection',
  'Parties',
  'Penetration (Protected)',
  'Pole Dancing',
  'Pregnant',
  'Prostate Massage',
  'Pussy Pumping',
  'Receiving Oral',
  'Rimming',
  'Rimming (giving)',
  'Rimming (receiving)',
  'Role Play & Fantasy*',
  'Sauna / Bath Houses',
  'Silent Caller (Phone Chat)',
  'Smoking (Fetish)',
  'Snowballing',
  'Spanking*',
  'Spanking (giving)*',
  'Spanking (receiving)*',
  'Strap On',
  'Striptease',
  'Sub games*',
  'Swallow',
  'Swallow (at discretion)',
  'Swinging',
  'Sybian & Machine Sex',
  'Tantric',
  'Tie & Tease*',
  'Toys',
  'Travel Companion',
  'Uniforms',
  'Unprotected Sex*',
  'Voyeurism',
  'Watersports*'
];
