export const nationalityToCode: { [key: string]: string } = {
    'afghan': 'AF',
    'albanian': 'AL',
    'algerian': 'DZ',
    'american': 'US',
    'andorran': 'AD',
    'angolan': 'AO',
    'antiguan': 'AG',
    'argentinian': 'AR',
    'armenian': 'AM',
    'australian': 'AU',
    'austrian': 'AT',
    'azerbaijani': 'AZ',
    'bahamian': 'BS',
    'bahraini': 'BH',
    'bangladeshi': 'BD',
    'barbadian': 'BB',
    'belarusian': 'BY',
    'belgian': 'BE',
    'belizean': 'BZ',
    'beninese': 'BJ',
    'bhutanese': 'BT',
    'bolivian': 'BO',
    'bosnian': 'BA',
    'botswanan': 'BW',
    'brazilian': 'BR',
    'british': 'GB',
    'bruneian': 'BN',
    'bulgarian': 'BG',
    'burkinabe': 'BF',
    'burmese': 'MM',
    'burundian': 'BI',
    'cambodian': 'KH',
    'cameroonian': 'CM',
    'canadian': 'CA',
    'cape verdean': 'CV',
    'central african': 'CF',
    'chadian': 'TD',
    'chilean': 'CL',
    'chinese': 'CN',
    'colombian': 'CO',
    'comorian': 'KM',
    'congolese': 'CG',
    'costa rican': 'CR',
    'croatian': 'HR',
    'cuban': 'CU',
    'cypriot': 'CY',
    'czech': 'CZ',
    'danish': 'DK',
    'djiboutian': 'DJ',
    'dominican': 'DO',
    'dutch': 'NL',
    'east timorese': 'TL',
    'ecuadorian': 'EC',
    'egyptian': 'EG',
    'emirian': 'AE',
    'equatorial guinean': 'GQ',
    'eritrean': 'ER',
    'estonian': 'EE',
    'ethiopian': 'ET',
    'fijian': 'FJ',
    'filipino': 'PH',
    'finnish': 'FI',
    'french': 'FR',
    'gabonese': 'GA',
    'gambian': 'GM',
    'georgian': 'GE',
    'german': 'DE',
    'ghanaian': 'GH',
    'greek': 'GR',
    'grenadian': 'GD',
    'guatemalan': 'GT',
    'guinean': 'GN',
    'guinea-bissauan': 'GW',
    'guyanese': 'GY',
    'haitian': 'HT',
    'honduran': 'HN',
    'hungarian': 'HU',
    'icelandic': 'IS',
    'indian': 'IN',
    'indonesian': 'ID',
    'iranian': 'IR',
    'iraqi': 'IQ',
    'irish': 'IE',
    'israeli': 'IL',
    'italian': 'IT',
    'ivorian': 'CI',
    'jamaican': 'JM',
    'japanese': 'JP',
    'jordanian': 'JO',
    'kazakhstani': 'KZ',
    'kenyan': 'KE',
    'kiribati': 'KI',
    'north korean': 'KP',
    'south korean': 'KR',
    'korean': 'KR',
    'kuwaiti': 'KW',
    'kyrgyz': 'KG',
    'laotian': 'LA',
    'latvian': 'LV',
    'lebanese': 'LB',
    'lesotho': 'LS',
    'liberian': 'LR',
    'libyan': 'LY',
    'liechtensteiner': 'LI',
    'lithuanian': 'LT',
    'luxembourgish': 'LU',
    'macedonian': 'MK',
    'malagasy': 'MG',
    'malawian': 'MW',
    'malaysian': 'MY',
    'maldivian': 'MV',
    'malian': 'ML',
    'maltese': 'MT',
    'marshallese': 'MH',
    'mauritanian': 'MR',
    'mauritian': 'MU',
    'mexican': 'MX',
    'micronesian': 'FM',
    'moldovan': 'MD',
    'monacan': 'MC',
    'mongolian': 'MN',
    'montenegrin': 'ME',
    'moroccan': 'MA',
    'mozambican': 'MZ',
    'namibian': 'NA',
    'nauruan': 'NR',
    'nepalese': 'NP',
    'new zealander': 'NZ',
    'nicaraguan': 'NI',
    'nigerien': 'NE',
    'nigerian': 'NG',
    'norwegian': 'NO',
    'omani': 'OM',
    'pakistani': 'PK',
    'palauan': 'PW',
    'palestinian': 'PS',
    'panamanian': 'PA',
    'papua new guinean': 'PG',
    'paraguayan': 'PY',
    'peruvian': 'PE',
    'polish': 'PL',
    'portuguese': 'PT',
    'qatari': 'QA',
    'romanian': 'RO',
    'russian': 'RU',
    'rwandan': 'RW',
    'saint kitts and nevis': 'KN',
    'saint lucian': 'LC',
    'saint vincent': 'VC',
    'samoan': 'WS',
    'san marinese': 'SM',
    'sao tomean': 'ST',
    'saudi': 'SA',
    'senegalese': 'SN',
    'serbian': 'RS',
    'seychellois': 'SC',
    'sierra leonean': 'SL',
    'singaporean': 'SG',
    'slovak': 'SK',
    'slovenian': 'SI',
    'solomon islander': 'SB',
    'somali': 'SO',
    'south african': 'ZA',
    'south sudanese': 'SS',
    'spanish': 'ES',
    'sri lankan': 'LK',
    'sudanese': 'SD',
    'surinamese': 'SR',
    'swazi': 'SZ',
    'swedish': 'SE',
    'swiss': 'CH',
    'syrian': 'SY',
    'tajik': 'TJ',
    'tanzanian': 'TZ',
    'thai': 'TH',
    'togolese': 'TG',
    'tongan': 'TO',
    'trinidadian': 'TT',
    'tunisian': 'TN',
    'turkish': 'TR',
    'turkmen': 'TM',
    'tuvaluan': 'TV',
    'ugandan': 'UG',
    'ukrainian': 'UA',
    'uruguayan': 'UY',
    'uzbek': 'UZ',
    'vanuatuan': 'VU',
    'vatican': 'VA',
    'venezuelan': 'VE',
    'vietnamese': 'VN',
    'yemeni': 'YE',
    'zambian': 'ZM',
    'zimbabwean': 'ZW',
    // Alternative spellings and common variations
    'american (us)': 'US',
    'american (usa)': 'US',
    'brit': 'GB',
    'united kingdom': 'GB',
    'english': 'GB',
    'scottish': 'GB',
    'welsh': 'GB',
    'northern irish': 'GB',
    'usa': 'US',
    'united states': 'US',
    'united states of america': 'US',
    'uk': 'GB',
    'uae': 'AE',
    'chinese (prc)': 'CN',
    'taiwanese': 'TW',
    'hong konger': 'HK',
    'macanese': 'MO'
};

// Helper function to normalize and look up nationality
export const getNationalityCode = (nationality: string): string | null => {
    if (!nationality) return null;
    const normalizedNationality = nationality.toLowerCase().trim();
    return nationalityToCode[normalizedNationality] || null;
};

// Helper function to get flag emoji from nationality
export const getNationalityFlag = (nationality: string): string => {
    const countryCode = getNationalityCode(nationality);
    if (!countryCode) return '';

    // Convert country code to regional indicator symbols
    const codePoints = countryCode
        .toUpperCase()
        .split('')
        .map(char => 127397 + char.charCodeAt(0));
    return String.fromCodePoint(...codePoints);
};